subtyping: subtyping.stanza
	stanza subtyping.stanza -o subtyping

iterating: iterating.stanza
	stanza iterating.stanza -o iterating

questions: questions.stanza
	stanza questions.stanza -o questions

max_subsum: max_subsum.stanza
	stanza max_subsum.stanza -o max_subsum

stack: stack.stanza
	stanza stack.stanza -o stack
